In [22]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [23]:
# Load the dataset
df = pd.read_csv('../data/ParisHousing.csv')
df.head()

,squareMeters,numberOfRooms,hasYard,hasPool,floors,cityCode,cityPartRange,numPrevOwners,made,isNewBuilt,hasStormProtector,basement,attic,garage,hasStorageRoom,hasGuestRoom,price
0,75523,3,0,1,63,9373,3,8,2005,0,1,4313,9005,956,0,7,7559081.5
1,80771,39,1,1,98,39381,8,6,2015,1,0,3653,2436,128,1,2,8085989.5
2,55712,58,0,1,19,34457,6,8,2021,0,0,2937,8852,135,1,9,5574642.1
3,32316,47,0,0,6,27939,10,4,2012,0,1,659,7141,359,0,3,3232561.2
4,70429,19,1,1,90,38045,3,7,1990,1,0,8435,2429,292,1,4,7055052.0

In [27]:
df.columns = df.columns.str.lower() # Lowercase for all columns
df.head()

,squaremeters,numberofrooms,hasyard,haspool,floors,citycode,citypartrange,numprevowners,made,isnewbuilt,hasstormprotector,basement,attic,garage,hasstorageroom,hasguestroom,price
0,75523,3,0,1,63,9373,3,8,2005,0,1,4313,9005,956,0,7,7559081.5
1,80771,39,1,1,98,39381,8,6,2015,1,0,3653,2436,128,1,2,8085989.5
2,55712,58,0,1,19,34457,6,8,2021,0,0,2937,8852,135,1,9,5574642.1
3,32316,47,0,0,6,27939,10,4,2012,0,1,659,7141,359,0,3,3232561.2
4,70429,19,1,1,90,38045,3,7,1990,1,0,8435,2429,292,1,4,7055052.0

In [26]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 17 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   squaremeters       10000 non-null  int64
 1   numberofrooms      10000 non-null  int64
 2   hasyard            10000 non-null  int64
 3   haspool            10000 non-null  int64
 4   floors             10000 non-null  int64
 5   citycode           10000 non-null  int64
 6   citypartrange      10000 non-null  int64
 7   numprevowners      10000 non-null  int64
 8   made               10000 non-null  int64
 9   isnewbuilt         10000 non-null  int64
 10  hasstormprotector  10000 non-null  int64
 11  basement           10000 non-null  int64
 12  attic              10000 non-null  int64
 13  garage             10000 non-null  int64
 14  hasstorageroom     10000 non-null  int64
 15  hasguestroom       10000 non-null  int64
 16  price              10000 non-null  float64
dtypes: float64(1), int64(16)
memory usage: 1.3 MB

### Check column wise

#### squaremeters

In [31]:
df.squaremeters.value_counts()

squaremeters
79770    3
33749    3
96526    3
16006    3
68985    3
        ..
21514    1
1726     1
44403    1
83841    1
59036    1
Name: count, Length: 9483, dtype: int64

In [32]:
df.squaremeters.nunique()

9483

In [33]:
# check missing values
df.squaremeters.isnull().sum()

np.int64(0)

#### numberofrooms

In [34]:
df.numberofrooms.value_counts()

numberofrooms
54    129
4     120
22    119
47    118
3     116
     ...
6      85
31     84
34     84
40     82
9      75
Name: count, Length: 100, dtype: int64

In [35]:
df.numberofrooms.nunique()

100

In [37]:
# check missing values
df.numberofrooms.isnull().sum()

np.int64(0)

#### hasyard

In [38]:
df.hasyard.value_counts()

hasyard
1    5087
0    4913
Name: count, dtype: int64

In [42]:
## check unique values
df.hasyard.nunique()

2

In [40]:
# check missing values
df.hasyard.isnull().sum()

np.int64(0)

#### haspool

In [43]:
df.haspool.value_counts()

haspool
0    5032
1    4968
Name: count, dtype: int64

In [45]:
df.haspool.nunique()

2

In [46]:
### check missing values
df.haspool.isnull().sum()

np.int64(0)

#### floors

In [47]:
df.floors.value_counts()

floors
97     126
55     122
77     117
3      116
28     116
      ...
15      83
74      83
48      83
100     82
92      75
Name: count, Length: 100, dtype: int64

In [48]:
df.floors.nunique()

100

In [49]:
df.floors.isnull().sum()

np.int64(0)

In [52]:
def column_summary_light(df):
    return pd.DataFrame({
        "missing_values": df.isna().sum(),
        "num_unique": df.nunique(),
        "dtype": df.dtypes
    }).reset_index().rename(columns={"index": "column"})

In [53]:
column_summary_light(df)

               column  missing_values  num_unique    dtype
0        squaremeters               0        9483    int64
1       numberofrooms               0         100    int64
2             hasyard               0           2    int64
3             haspool               0           2    int64
4              floors               0         100    int64
5            citycode               0        9509    int64
6       citypartrange               0          10    int64
7       numprevowners               0          10    int64
8                made               0          32    int64
9          isnewbuilt               0           2    int64
10  hasstormprotector               0           2    int64
11           basement               0        6352    int64
12              attic               0        6267    int64
13             garage               0         901    int64
14     hasstorageroom               0           2    int64
15       hasguestroom               0          11    int64
16              price               0       10000  float64

In [56]:
df.describe()

,squaremeters,numberofrooms,hasyard,haspool,floors,citycode,citypartrange,numprevowners,made,isnewbuilt,hasstormprotector,basement,attic,garage,hasstorageroom,hasguestroom,price
count,10000.00000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000,10000.00000,10000.00000,10000.000000,10000.00000,1.000000e+04
mean,49870.13120,50.358400,0.508700,0.496800,50.276300,50225.486100,5.510100,5.521700,2005.48850,0.499100,0.499900,5033.103900,5028.01060,553.12120,0.503000,4.99460,4.993448e+06
std,28774.37535,28.816696,0.499949,0.500015,28.889171,29006.675799,2.872024,2.856667,9.30809,0.500024,0.500025,2876.729545,2894.33221,262.05017,0.500016,3.17641,2.877424e+06
min,89.00000,1.000000,0.000000,0.000000,1.000000,3.000000,1.000000,1.000000,1990.00000,0.000000,0.000000,0.000000,1.00000,100.00000,0.000000,0.00000,1.031350e+04
25%,25098.50000,25.000000,0.000000,0.000000,25.000000,24693.750000,3.000000,3.000000,1997.00000,0.000000,0.000000,2559.750000,2512.00000,327.75000,0.000000,2.00000,2.516402e+06
50%,50105.50000,50.000000,1.000000,0.000000,50.000000,50693.000000,5.000000,5.000000,2005.50000,0.000000,0.000000,5092.500000,5045.00000,554.00000,1.000000,5.00000,5.016180e+06
75%,74609.75000,75.000000,1.000000,1.000000,76.000000,75683.250000,8.000000,8.000000,2014.00000,1.000000,1.000000,7511.250000,7540.50000,777.25000,1.000000,8.00000,7.469092e+06
max,99999.00000,100.000000,1.000000,1.000000,100.000000,99953.000000,10.000000,10.000000,2021.00000,1.000000,1.000000,10000.000000,10000.00000,1000.00000,1.000000,10.00000,1.000677e+07

In [67]:
df[df['floors'] >= 76]

,squaremeters,numberofrooms,hasyard,haspool,floors,citycode,citypartrange,numprevowners,made,isnewbuilt,hasstormprotector,basement,attic,garage,hasstorageroom,hasguestroom,price
1,80771,39,1,1,98,39381,8,6,2015,1,0,3653,2436,128,1,2,8085989.5
4,70429,19,1,1,90,38045,3,7,1990,1,0,8435,2429,292,1,4,7055052.0
6,58682,10,1,1,99,6450,10,9,1995,1,1,5930,9453,848,0,5,5876376.5
10,23563,21,0,1,90,91058,6,8,1993,1,0,703,852,684,1,10,2366397.3
13,13087,44,1,0,77,40475,8,4,2004,1,0,1745,724,582,0,0,1320803.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9980,82333,28,0,0,78,23385,3,7,2007,1,1,7022,6276,566,1,6,8236936.7
9983,87627,56,1,0,95,33850,9,9,2015,1,0,2522,988,735,0,9,8766795.5
9989,90996,81,1,1,80,1085,3,9,1990,0,1,8633,2007,689,0,5,9112369.0
9992,33545,55,0,1,79,8288,1,2,2006,1,0,3480,4046,946,1,6,3361070.6
9998,59036,70,0,0,96,55856,1,3,2010,0,1,2590,6174,339,1,4,5905107.0

In [71]:
len(df)

10000

### Setting Up Validation Framework

In [68]:
from sklearn.model_selection import train_test_split

In [69]:
df_full_train, df_test = train_test_split(df, test_size= 0.2, random_state=42)
df_train, df_val = train_test_split(df_full_train, test_size=0.25, random_state=42)

In [70]:
len(df_full_train), len(df_test), len(df_train), len(df_val)

(8000, 2000, 6000, 2000)

In [73]:
df_val

,squaremeters,numberofrooms,hasyard,haspool,floors,citycode,citypartrange,numprevowners,made,isnewbuilt,hasstormprotector,basement,attic,garage,hasstorageroom,hasguestroom,price
3188,8537,59,1,0,49,19292,9,8,1998,1,1,3152,3491,238,0,7,859540.8
8293,72381,93,0,1,20,32337,6,3,2010,0,0,2130,7783,256,0,8,7242040.0
1710,77913,6,0,0,82,89070,9,3,2010,0,0,6930,9386,561,1,9,7794411.0
7510,83776,21,1,1,33,64605,2,9,2020,0,1,4170,3657,577,0,10,8381763.0
1461,83197,46,1,1,68,36740,7,5,1997,1,0,4439,9572,351,1,2,8327908.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2834,23184,56,1,1,100,70418,7,9,1997,0,1,7131,4031,762,1,3,2335644.7
449,15542,19,0,0,27,48610,8,7,1996,0,0,563,6368,615,0,5,1556824.6
6686,16205,88,0,0,11,98132,8,2,2013,1,1,9455,8208,986,1,8,1621809.3
3561,30291,10,0,0,24,14914,4,8,1997,0,1,9572,7717,374,0,7,3030131.7
9595,14945,33,1,1,3,54997,4,9,2015,0,0,6989,9351,678,0,8,1501436.5

In [74]:
df_train = df_train.reset_index(drop=True)
df_val = df_val.reset_index(drop=True)
df_test = df_test.reset_index(drop=True)

In [75]:
y_train = df_train.price
y_val = df_val.price
y_test = df_test.price